Movie/anime/anime/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('animewatch.urls'))
]
if settings.DEBUG:
        urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
        urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

Movie/anime/animewatch/urls.py
from django.urls import path

from .import views
app_name='animewatch'

urlpatterns = [

    path('',views.index,name='index'),
    path('movie/<int:movieid>/',views.detail,name='detail'),
    path('add/', views.add_anime, name='add_anime'),
    path('update/<int:id>/',views.update,name='update'),
    path('delete/<int:id>/', views.delete, name='delete')

]

Movie/anime/animewatch/models.py
from django.db import models

# Create your models here.
class anime(models.Model):
    name=models.CharField(max_length=100)
    desc=models.TextField()
    year=models.IntegerField()
    img=models.ImageField(upload_to='gallery')

    def __str__(self):
        return self.name

Movie/anime/animewatch/forms.py
from django import forms
from.models import anime

class AnimeForm(forms.ModelForm):
    class Meta:
        model=anime
        fields=['name','desc','year','img']

Movie/anime/animewatch/views.py
import anime
from django.http import HttpResponse
from django.shortcuts import render, redirect
from .models import anime
from.  forms import AnimeForm

# Create your views here.
def index(request):
    Anime=anime.objects.all()
    context={
        'anime_list':Anime
    }
    return render(request,'index.html',context)
def detail(request,movieid):
    Anime=anime.objects.get(id=movieid)
    return render(request,'detail.html',{'Anime':Anime})
def add_anime(request):
    if request.method=="POST":
        name=request.POST.get('name')
        desc=request.POST.get('desc')
        year=request.POST.get('year')
        img=request.FILES['img']
        Anime = anime(name=name,desc=desc,year=year,img=img)
        Anime.save()
        return redirect('/')
    return render(request,'add.html')
def update(request,id):
    Anime=anime.objects.get(id=id)
    form=AnimeForm(request.POST or None,request.FILES,instance=Anime)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request,'edit.html',{'form':form,'Anime':Anime})
def delete(request,id):
    if request.method=="POST":
        Anime=anime.objects.get(id=id)
        Anime.delete()
        return redirect('/')
    return render(request,'delete.html')

Movie/anime/templates/add.html
{% extends 'base.html' %}
{% block body %}
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="text" name="name" placeholder="Enter your Anime Name">
    <input type="text" name="desc" placeholder="Enter your Anime Description">
    <input type="text" name="year" placeholder="Enter your Anime Released year">
    <input type="file" name="img" >
    <input type="submit" placeholder="ADD">

</form>
{% endblock %}

Movie/anime/templates/base.html
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Animewatch</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
<nav class="navbar navbar-dark bg-dark">
    <a class="navbar-brand" href="#">
        Online Anime Store
      Bootstrap
<a class="btn btn-warning" href="{% url 'animewatch:add_anime'%}">Add</a>


    </a>
  </div>
</nav>
{% block body %}
{% endblock %}

</body>
</html>

Movie/anime/templates/delete.html
<form method="POST">
    {% csrf_token %}
    Are you sure want to delete the anime?
    <input type="submit">
</form>

Movie/anime/templates/detail.html
{% extends 'base.html' %}
{% block body %}

<div class="container">
    <div class="row">
        <div class="col-md-6">
            <img src="{{Anime.img.url}}" width="250" height="300">
        </div>

 <div class="col-md-6">
<h4>{{Anime.name}}</h4>
     <h6>{{Anime.desc}}</h6>
{{Anime.year}}
<a class="btn btn-warning" href="{% url 'animewatch:update' Anime.id %}">update</a>
<a class="btn btn-warning" href="{% url 'animewatch:delete' Anime.id %}">delete</a>

 </div>
    </div>
</div>


{% endblock %}

Movie/anime/templates/edit.html
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit">
</form>

Movie/anime/templates/index.html
{% extends 'base.html' %}
{% block body %}

<div class="container">
    <div class="row">
        {% for i in anime_list %}
            <div class="col-md-4">
                <div class="card" style="width: 18rem;">
                    <img class="card-img-top" src="{{i.img.url}}" alt="Card image cap" width="100" height="300">
                    <div class="card-body">
                        <h5 class="card-title">{{i.name}}</h5>
                        <p class="card-text">{{i.desc}}</p>
                        <a href="{% url 'animewatch:detail' i.id %}" class="btn btn-primary">SELECT</a>

                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock %}